Dir {
  ArchiveDir ".";
  CacheDir "cache";
}

Default {
  Packages::Compress ". gzip xz";
  Sources::Compress ". gzip xz";
  Contents::Compress ". gzip xz";
}

TreeDefault {
  Directory "pool/$(SECTION)";
}

Tree "dists/jammy" {
  Sections "main";
  Architectures "amd64 arm64 source";
}

Tree "dists/noble" {
  Sections "main";
  Architectures "amd64 arm64 source";
}

APT::FTPArchive::Release {
  Origin "Lara Nux";
  Label "Lara Nux";
  Suite "stable";
  Components "main";
  Architectures "amd64 arm64 source";
  Description "Signed Ubuntu packages for Lara Nux";
}
